name: Metrics
on:
  # Update every 24 hours
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Push updates when you change your README
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: your-github-username-here  # <--- CHANGE THIS
          template: classic
          base: header, activity, community, repositories, metadata
          
          # This enables the 4-quadrant radar chart
          plugin_introduction: yes
          plugin_introduction_title: yes
